In [1]:
import pandas as pd

In [2]:
orders = pd.read_csv("orders.csv")
orders.head()

  order_id customer_id product_id  quantity  order_date
0   O00001       C0333       P022         1  2022-01-09
1   O00002       C0068       P090         1  2022-01-27
2   O00003       C0483       P021         1  2022-01-17
3   O00004       C0214       P076         4  2022-01-07
4   O00005       C0411       P073         4  2022-01-12

In [4]:
orders.shape

(2584, 5)

In [5]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 2584 entries, 0 to 2583
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     2584 non-null   str
 1   customer_id  2584 non-null   str
 2   product_id   2584 non-null   str
 3   quantity     2584 non-null   int64
 4   order_date   2584 non-null   str
dtypes: int64(1), str(4)
memory usage: 101.1 KB

In [11]:
orders["order_date"] = pd.to_datetime(orders.order_date)

In [12]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 2584 entries, 0 to 2583
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     2584 non-null   str
 1   customer_id  2584 non-null   str
 2   product_id   2584 non-null   str
 3   quantity     2584 non-null   int64
 4   order_date   2584 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(1), str(3)
memory usage: 101.1 KB

In [13]:
orders['year'] = orders.order_date.dt.year
orders['month'] = orders.order_date.dt.month

In [14]:
orders.head()

  order_id customer_id product_id  quantity order_date  year  month
0   O00001       C0333       P022         1 2022-01-09  2022      1
1   O00002       C0068       P090         1 2022-01-27  2022      1
2   O00003       C0483       P021         1 2022-01-17  2022      1
3   O00004       C0214       P076         4 2022-01-07  2022      1
4   O00005       C0411       P073         4 2022-01-12  2022      1

In [17]:
orders.year.unique()

array([2022, 2023, 2024], dtype=int32)

In [21]:
prod_count = orders.product_id.value_counts()

In [27]:
max_prod = prod_count[prod_count == prod_count.max()]

In [31]:
max_prod = max_prod.index[0]

In [32]:
max_prod

'P041'

In [34]:
products = pd.read_csv("products.csv")
products.head()

  product_id product_name     category   price
0       P001        Stage     Clothing  534.93
1       P002        Least  Accessories   56.56
2       P003       Number         Home  339.92
3       P004      Evening     Clothing  138.74
4       P005      Protect     Footwear   68.06

In [36]:
print("Most Saling product")
products[products.product_id == max_prod]

Most Saling product

   product_id product_name  category   price
40       P041       Behind  Footwear  465.37

In [37]:
orders.head()

  order_id customer_id product_id  quantity order_date  year  month
0   O00001       C0333       P022         1 2022-01-09  2022      1
1   O00002       C0068       P090         1 2022-01-27  2022      1
2   O00003       C0483       P021         1 2022-01-17  2022      1
3   O00004       C0214       P076         4 2022-01-07  2022      1
4   O00005       C0411       P073         4 2022-01-12  2022      1

In [39]:
grouped_orders = orders.groupby("year")

In [44]:
_2022 = grouped_orders.get_group(2022)

In [42]:
grouped_orders.get_group(2023)

     order_id customer_id product_id  quantity order_date  year  month
828    O00829       C0373       P033         4 2023-01-22  2023      1
829    O00830       C0010       P064         2 2023-01-25  2023      1
830    O00831       C0335       P082         1 2023-01-29  2023      1
831    O00832       C0478       P005         4 2023-01-21  2023      1
832    O00833       C0137       P020         3 2023-01-19  2023      1
...       ...         ...        ...       ...        ...   ...    ...
1747   O01748       C0168       P086         4 2023-12-10  2023     12
1748   O01749       C0249       P060         1 2023-12-27  2023     12
1749   O01750       C0043       P071         2 2023-12-12  2023     12
1750   O01751       C0366       P057         2 2023-12-26  2023     12
1751   O01752       C0242       P036         2 2023-12-13  2023     12

[924 rows x 7 columns]

In [43]:
grouped_orders.get_group(2024)

     order_id customer_id product_id  quantity order_date  year  month
1752   O01753       C0009       P054         1 2024-01-27  2024      1
1753   O01754       C0008       P044         2 2024-01-01  2024      1
1754   O01755       C0349       P086         1 2024-01-20  2024      1
1755   O01756       C0113       P013         2 2024-01-04  2024      1
1756   O01757       C0371       P022         1 2024-01-06  2024      1
...       ...         ...        ...       ...        ...   ...    ...
2579   O02580       C0237       P098         5 2024-12-22  2024     12
2580   O02581       C0236       P007         1 2024-12-05  2024     12
2581   O02582       C0029       P035         1 2024-12-12  2024     12
2582   O02583       C0171       P077         1 2024-12-16  2024     12
2583   O02584       C0421       P038         5 2024-12-01  2024     12

[832 rows x 7 columns]

In [46]:
rc_2022 = _2022.customer_id.value_counts()

In [48]:
rc_2022[rc_2022 > 1].shape

(240,)

In [51]:
print("Total orders:",_2022.shape[0])

Total orders: 828

In [52]:
print("Total Quantity",_2022.quantity.sum())

Total Quantity 2549

In [70]:
_2022_prod = _2022.groupby('product_id')

In [90]:
_2022_prod_sale = {}

In [93]:
for pid in _2022_prod.product_id.unique():
    print(f"Total sales of {pid[0]}: {_2022_prod.get_group(pid[0]).quantity.sum()}")
    _2022_prod_sale[pid[0]] = _2022_prod.get_group(pid[0]).quantity.sum()

Total sales of P001: 20
Total sales of P002: 22
Total sales of P003: 22
Total sales of P004: 17
Total sales of P005: 11
Total sales of P006: 33
Total sales of P007: 13
Total sales of P008: 12
Total sales of P009: 29
Total sales of P010: 16
Total sales of P011: 23
Total sales of P012: 18
Total sales of P013: 24
Total sales of P014: 32
Total sales of P015: 27
Total sales of P016: 20
Total sales of P017: 18
Total sales of P018: 26
Total sales of P019: 17
Total sales of P020: 22
Total sales of P021: 23
Total sales of P022: 44
Total sales of P023: 10
Total sales of P024: 33
Total sales of P025: 27
Total sales of P026: 10
Total sales of P027: 31
Total sales of P028: 22
Total sales of P029: 19
Total sales of P030: 18
Total sales of P031: 41
Total sales of P032: 12
Total sales of P033: 24
Total sales of P034: 30
Total sales of P035: 21
Total sales of P036: 12
Total sales of P037: 28
Total sales of P038: 15
Total sales of P039: 26
Total sales of P040: 12
Total sales of P041: 44
Total sales of P042: 27
Total sales of P043: 23
Total sales of P044: 29
Total sales of P045: 27
Total sales of P046: 30
Total sales of P047: 23
Total sales of P048: 17
Total sales of P049: 29
Total sales of P050: 23
Total sales of P051: 23
Total sales of P052: 26
Total sales of P053: 30
Total sales of P054: 10
Total sales of P055: 20
Total sales of P056: 38
Total sales of P057: 33
Total sales of P058: 34
Total sales of P059: 59
Total sales of P060: 11
Total sales of P061: 23
Total sales of P062: 36
Total sales of P063: 22
Total sales of P064: 10
Total sales of P065: 26
Total sales of P066: 27
Total sales of P067: 20
Total sales of P068: 15
Total sales of P069: 37
Total sales of P070: 36
Total sales of P071: 25
Total sales of P072: 35
Total sales of P073: 24
Total sales of P074: 44
Total sales of P075: 24
Total sales of P076: 27
Total sales of P077: 28
Total sales of P078: 22
Total sales of P079: 37
Total sales of P080: 27
Total sales of P081: 32
Total sales of P082: 32
Total sales of P083: 37
Total sales of P084: 35
Total sales of P085: 41
Total sales of P086: 28
Total sales of P087: 38
Total sales of P088: 22
Total sales of P089: 23
Total sales of P090: 41
Total sales of P091: 30
Total sales of P092: 14
Total sales of P093: 26
Total sales of P094: 15
Total sales of P095: 18
Total sales of P096: 30
Total sales of P097: 36
Total sales of P098: 8
Total sales of P099: 43
Total sales of P100: 19

In [94]:
_2022_prod_sale

{'P001': np.int64(20),
 'P002': np.int64(22),
 'P003': np.int64(22),
 'P004': np.int64(17),
 'P005': np.int64(11),
 'P006': np.int64(33),
 'P007': np.int64(13),
 'P008': np.int64(12),
 'P009': np.int64(29),
 'P010': np.int64(16),
 'P011': np.int64(23),
 'P012': np.int64(18),
 'P013': np.int64(24),
 'P014': np.int64(32),
 'P015': np.int64(27),
 'P016': np.int64(20),
 'P017': np.int64(18),
 'P018': np.int64(26),
 'P019': np.int64(17),
 'P020': np.int64(22),
 'P021': np.int64(23),
 'P022': np.int64(44),
 'P023': np.int64(10),
 'P024': np.int64(33),
 'P025': np.int64(27),
 'P026': np.int64(10),
 'P027': np.int64(31),
 'P028': np.int64(22),
 'P029': np.int64(19),
 'P030': np.int64(18),
 'P031': np.int64(41),
 'P032': np.int64(12),
 'P033': np.int64(24),
 'P034': np.int64(30),
 'P035': np.int64(21),
 'P036': np.int64(12),
 'P037': np.int64(28),
 'P038': np.int64(15),
 'P039': np.int64(26),
 'P040': np.int64(12),
 'P041': np.int64(44),
 'P042': np.int64(27),
 'P043': np.int64(23),
 'P044': np.int64(29),
 'P045': np.int64(27),
 'P046': np.int64(30),
 'P047': np.int64(23),
 'P048': np.int64(17),
 'P049': np.int64(29),
 'P050': np.int64(23),
 'P051': np.int64(23),
 'P052': np.int64(26),
 'P053': np.int64(30),
 'P054': np.int64(10),
 'P055': np.int64(20),
 'P056': np.int64(38),
 'P057': np.int64(33),
 'P058': np.int64(34),
 'P059': np.int64(59),
 'P060': np.int64(11),
 'P061': np.int64(23),
 'P062': np.int64(36),
 'P063': np.int64(22),
 'P064': np.int64(10),
 'P065': np.int64(26),
 'P066': np.int64(27),
 'P067': np.int64(20),
 'P068': np.int64(15),
 'P069': np.int64(37),
 'P070': np.int64(36),
 'P071': np.int64(25),
 'P072': np.int64(35),
 'P073': np.int64(24),
 'P074': np.int64(44),
 'P075': np.int64(24),
 'P076': np.int64(27),
 'P077': np.int64(28),
 'P078': np.int64(22),
 'P079': np.int64(37),
 'P080': np.int64(27),
 'P081': np.int64(32),
 'P082': np.int64(32),
 'P083': np.int64(37),
 'P084': np.int64(35),
 'P085': np.int64(41),
 'P086': np.int64(28),
 'P087': np.int64(38),
 'P088': np.int64(22),
 'P089': np.int64(23),
 'P090': np.int64(41),
 'P091': np.int64(30),
 'P092': np.int64(14),
 'P093': np.int64(26),
 'P094': np.int64(15),
 'P095': np.int64(18),
 'P096': np.int64(30),
 'P097': np.int64(36),
 'P098': np.int64(8),
 'P099': np.int64(43),
 'P100': np.int64(19)}

In [95]:
_2022_prod_sale = pd.Series(_2022_prod_sale)

In [96]:
_2022_prod_sale

P001    20
P002    22
P003    22
P004    17
P005    11
        ..
P096    30
P097    36
P098     8
P099    43
P100    19
Length: 100, dtype: int64

In [103]:
print(f"Most Saling product in 2022 by quantity: {_2022_prod_sale.index[_2022_prod_sale.argmax()]}")

Most Saling product in 2022 by quantity: P059

In [116]:
for year in orders.year.unique():
    year_data = grouped_orders.get_group(year)
    prod_group = year_data.groupby('product_id')
    prod_sales = {}
    for pid in prod_group.product_id.unique():
        prod_sales[pid[0]] = prod_group.get_group(pid[0]).quantity.sum()
    prod_sales = pd.Series(prod_sales)
    print(f"Most Saling product in {year} by quantity: {prod_sales.index[prod_sales.argmax()]}")

Most Saling product in 2022 by quantity: P059
Most Saling product in 2023 by quantity: P091
Most Saling product in 2024 by quantity: P041

In [125]:
for year, year_data in grouped_orders:
    best = year_data.groupby('product_id')["quantity"].sum().idxmax()
    print(f"Most Saling product in {year} by quantity: {best}")

Most Saling product in 2022 by quantity: P059
Most Saling product in 2023 by quantity: P091
Most Saling product in 2024 by quantity: P041