In [2]:
import pandas as pd

In [2]:
calories = pd.read_csv("calories.csv")

In [3]:
calories

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [22]:
data = [["Yasir","Nawaz",50,60,80,50,90],
        ["Yasir1","Nawaz",89,90,40,70,60],
        ["Yasir1","Nawaz",89,90,40,70,60],
        ["Yasir1","Nawaz",89,90,40,70,60],
        ["Yasir1","Nawaz",89,90,40,70,60],
        ["Yasir2","Nawaz",90,50,60,80,70]]

In [23]:
df = pd.DataFrame(data,columns=["Name","FName","S1","S2","S3","S4","S5"],index=[f"std{x}" for x in range(len(data))])

In [24]:
df

        Name  FName  S1  S2  S3  S4  S5
std0   Yasir  Nawaz  50  60  80  50  90
std1  Yasir1  Nawaz  89  90  40  70  60
std2  Yasir1  Nawaz  89  90  40  70  60
std3  Yasir1  Nawaz  89  90  40  70  60
std4  Yasir1  Nawaz  89  90  40  70  60
std5  Yasir2  Nawaz  90  50  60  80  70

In [21]:
se = pd.Series([1,2,3])

In [22]:
se

0    1
1    2
2    3
dtype: int64

In [27]:
data = [{"Name":"Yasir","FName":"Nawaz","S1":50,"S2":60,"S3":80,"S4":50,"S5":90},
       {"Name":"Yasir","FName":"Nawaz","S1":50,"S2":60,"S3":80,"S4":50,"S5":90},
       {"Name":"Yasir","FName":"Nawaz","S1":50,"S2":60,"S3":80,"S4":50,"S5":90},
       {"Name":"Yasir","FName":"Nawaz","S1":50,"S2":60,"S3":80,"S4":50,"S5":90}]

In [28]:
df1 = pd.DataFrame(data)

In [29]:
df1

    Name  FName  S1  S2  S3  S4  S5
0  Yasir  Nawaz  50  60  80  50  90
1  Yasir  Nawaz  50  60  80  50  90
2  Yasir  Nawaz  50  60  80  50  90
3  Yasir  Nawaz  50  60  80  50  90

In [105]:
calories = pd.read_csv("calories.csv")

In [50]:
calories.head(10)

   Duration  Pulse  Maxpulse  Calories
0        60  110.0     130.0     409.1
1        60  117.0     145.0     479.0
2        60  103.0     135.0     340.0
3        45  109.0     175.0     282.4
4        45  117.0     148.0     406.0
5        60  102.0     127.0     300.0
6        60  110.0     136.0     374.0
7        40  104.0     134.0     253.3
8        30  109.0     133.0     195.1
9        60   98.0     124.0     269.0

In [7]:
calories.tail(10)

     Duration  Pulse  Maxpulse  Calories
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [78]:
calories.dtypes

Duration      int64
Pulse       float64
Maxpulse    float64
Calories        str
dtype: object

In [10]:
calories.shape

(169, 4)

In [12]:
list(calories.columns)

['Duration', 'Pulse', 'Maxpulse', 'Calories']

In [13]:
list(calories.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168]

In [14]:
calories["Duration"]

0      60
1      60
2      60
3      45
4      45
       ..
164    60
165    60
166    60
167    75
168    75
Name: Duration, Length: 169, dtype: int64

In [38]:
calories[["Duration","Calories"]]

     Duration  Calories
0          60     409.1
1          60     479.0
2          60     340.0
3          45     282.4
4          45     406.0
..        ...       ...
164        60     290.8
165        60     300.0
166        60     310.2
167        75     320.4
168        75     330.4

[169 rows x 2 columns]

In [15]:
calories.Duration

0      60
1      60
2      60
3      45
4      45
       ..
164    60
165    60
166    60
167    75
168    75
Name: Duration, Length: 169, dtype: int64

In [18]:
calories.iloc[:,-1]

0      409.1
1      479.0
2      340.0
3      282.4
4      406.0
       ...
164    290.8
165    300.0
166    310.2
167    320.4
168    330.4
Name: Calories, Length: 169, dtype: float64

In [45]:
calories.iloc[:,[-1,-2]]      # calories.iloc[:,0:2]

     Pulse  Maxpulse
0      110       130
1      117       145
2      103       135
3      109       175
4      117       148
..     ...       ...
164    105       140
165    110       145
166    115       145
167    120       150
168    125       150

[169 rows x 2 columns]

In [30]:
df

        Name  FName  S1  S2  S3  S4  S5
std0   Yasir  Nawaz  50  60  80  50  90
std1  Yasir1  Nawaz  89  90  40  70  60
std2  Yasir1  Nawaz  89  90  40  70  60
std3  Yasir1  Nawaz  89  90  40  70  60
std4  Yasir1  Nawaz  89  90  40  70  60
std5  Yasir2  Nawaz  90  50  60  80  70

In [46]:
df.loc[["std0","std3"]]

        Name  FName  S1  S2  S3  S4  S5
std0   Yasir  Nawaz  50  60  80  50  90
std3  Yasir1  Nawaz  89  90  40  70  60

In [48]:
df.iloc[1:3,0:2]

        Name  FName
std1  Yasir1  Nawaz
std2  Yasir1  Nawaz

In [54]:
calories.Pulse * 2

0      220.0
1      234.0
2      206.0
3      218.0
4      234.0
       ...
164    210.0
165    220.0
166    230.0
167    240.0
168    250.0
Name: Pulse, Length: 169, dtype: float64

In [77]:
calories.loc[10]

Duration            60
Pulse            103.0
Maxpulse         147.0
Calories    hbskjhbvjs
Name: 10, dtype: object

In [69]:
calories.isna().sum()

Duration    0
Pulse       4
Maxpulse    1
Calories    3
dtype: int64

In [93]:
# calories.fillna(0,inplace=True)

cal_mean = calories.mean()
print(cal_mean)
calories.fillna(cal_mean, inplace= True).iloc[10]

Duration     63.816568
Pulse       107.612121
Maxpulse    134.142857
Calories    367.869277
dtype: float64

Duration     60.000000
Pulse       103.000000
Maxpulse    147.000000
Calories    367.869277
Name: 10, dtype: float64

In [66]:
calories.loc[21]

Duration     45.0
Pulse         0.0
Maxpulse    119.0
Calories    282.0
Name: 21, dtype: float64

In [82]:
calories.Calories.astype(float,errors='ignore')

0      409.1
1        479
2        340
3      282.4
4        406
       ...
164    290.8
165      300
166    310.2
167    320.4
168    330.4
Name: Calories, Length: 169, dtype: str

In [87]:
calories["Calories"] = pd.to_numeric(calories.Calories, errors= 'coerce')

In [88]:
calories.dtypes

Duration      int64
Pulse       float64
Maxpulse    float64
Calories    float64
dtype: object

In [91]:
calories.Calories.astype(str)   # used to convert into any dtypes.

0      409.1
1      479.0
2      340.0
3      282.4
4      406.0
       ...
164    290.8
165    300.0
166    310.2
167    320.4
168    330.4
Name: Calories, Length: 169, dtype: object

In [94]:
calories.isna().sum()

Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [106]:
calories.mean()

Duration     63.816568
Pulse       107.612121
Maxpulse    134.142857
Calories    363.598802
dtype: float64

In [104]:
calories.median()

Duration     60.0
Pulse       105.0
Maxpulse    131.0
Calories    310.2
dtype: float64

In [101]:
calories.mode()

   Duration  Pulse  Maxpulse  Calories
0        60  100.0     120.0     300.0

In [107]:
calories.std()

Duration       42.314955
Pulse          14.564234
Maxpulse       16.452540
Calories    10979.670860
dtype: float64

In [108]:
calories.var()

Duration    1.790555e+03
Pulse       2.121169e+02
Maxpulse    2.706861e+02
Calories    1.205532e+08
dtype: float64

In [129]:
data = [[50,60,80,50,90],
        [89,90,40,70,60],
        [89,90,40,70,60],
        [89,90,40,70,40],
        [89,90,40,70,60],
        [90,50,60,80,70]]
data_df = pd.DataFrame(data,columns=["s1","s2","s3","s4","s5"])

In [130]:
data_df.dtypes

s1    int64
s2    int64
s3    int64
s4    int64
s5    int64
dtype: object

In [131]:
# data_df.prod()
# data_df.pow(2)
data_df.sum(axis=1,numeric_only=True)

0    330
1    349
2    349
3    329
4    349
5    350
dtype: int64

In [132]:
data_df.corr()

          s1        s2        s3        s4        s5
s1  1.000000  0.467552 -0.866090  0.923381 -0.790569
s2  0.467552  1.000000 -0.846826  0.092387 -0.711991
s3 -0.866090 -0.846826  1.000000 -0.607831  0.878310
s4  0.923381  0.092387 -0.607831  1.000000 -0.581318
s5 -0.790569 -0.711991  0.878310 -0.581318  1.000000

In [1]:
student = [{"Name":"Ahmed","Fname":"Ali","FinalMarks":80,"Grade":"A"},
           {"Name":"Ahmed","Fname":"Ali","FinalMarks":80,"Grade":"B"},
           {"Name":"Ahmed","Fname":"Ali","FinalMarks":"Fail","Grade":"A"},
           {"Name":"Ahmed","Fname":"Ali","FinalMarks":80,"Grade":"B"},
           {"Name":"Ahmed","Fname":"Ali","FinalMarks":80,"Grade":"A"}]

In [30]:
std_df = pd.DataFrame(student)
std_df

    Name Fname FinalMarks Grade
0  Ahmed   Ali         80     A
1  Ahmed   Ali         80     B
2  Ahmed   Ali       Fail     A
3  Ahmed   Ali         80     B
4  Ahmed   Ali         80     A

In [5]:
std_df.pop("Grade")

0    A
1    B
2    A
3    B
4    A
Name: Grade, dtype: str

In [6]:
std_df

    Name Fname FinalMarks
0  Ahmed   Ali         80
1  Ahmed   Ali         80
2  Ahmed   Ali       Fail
3  Ahmed   Ali         80
4  Ahmed   Ali         80

In [13]:
std_df.drop(["Grade",'Fname'], axis = 1, errors='ignore')

    Name FinalMarks
0  Ahmed         80
1  Ahmed         80
2  Ahmed       Fail
3  Ahmed         80
4  Ahmed         80

In [31]:
std_df["FinalMarks"] = pd.to_numeric(std_df.FinalMarks, errors='coerce')

In [32]:
std_df.dtypes

Name              str
Fname             str
FinalMarks    float64
Grade             str
dtype: object

In [33]:
df = std_df.dropna()

In [36]:
df.reset_index(drop=True)

    Name Fname  FinalMarks Grade
0  Ahmed   Ali        80.0     A
1  Ahmed   Ali        80.0     B
2  Ahmed   Ali        80.0     B
3  Ahmed   Ali        80.0     A

In [37]:
df.Grade.unique()

<StringArray>
['A', 'B']
Length: 2, dtype: str

In [38]:
df.Grade.value_counts()

Grade
A    2
B    2
Name: count, dtype: int64

In [39]:
df.Grade.count()

np.int64(4)

In [101]:
student_data = pd.read_csv("student_marks.csv",na_values='abcent')
student_data.head()

         roll_no                  name  quiz_1  quiz_2  quiz_3  final_exam
0  SMIT/DSAI/001         Thomas Mcneil     6.0     1.0     6.0         6.0
1  SMIT/DSAI/002       Brian Davis Jr.     3.0     2.0     7.0         3.0
2  SMIT/DSAI/003  Christopher Thompson    10.0     8.0     2.0         7.0
3  SMIT/DSAI/004          Thomas Ortiz     7.0    -2.0     5.0        19.0
4  SMIT/DSAI/005      Benjamin Aguirre     4.0     3.0     0.0        28.0

In [102]:
student_data.shape

(500, 6)

In [103]:
student_data.dtypes

roll_no           str
name              str
quiz_1        float64
quiz_2        float64
quiz_3        float64
final_exam    float64
dtype: object

In [104]:
student_data.isna().sum()

roll_no        0
name           0
quiz_1        50
quiz_2        50
quiz_3        49
final_exam    50
dtype: int64

In [105]:
student_data.fillna(0,inplace=True)

           roll_no                  name  quiz_1  quiz_2  quiz_3  final_exam
0    SMIT/DSAI/001         Thomas Mcneil     6.0     1.0     6.0         6.0
1    SMIT/DSAI/002       Brian Davis Jr.     3.0     2.0     7.0         3.0
2    SMIT/DSAI/003  Christopher Thompson    10.0     8.0     2.0         7.0
3    SMIT/DSAI/004          Thomas Ortiz     7.0    -2.0     5.0        19.0
4    SMIT/DSAI/005      Benjamin Aguirre     4.0     3.0     0.0        28.0
..             ...                   ...     ...     ...     ...         ...
495  SMIT/DSAI/496           Rita Torres     9.0     9.0     7.0         0.0
496  SMIT/DSAI/497           Paul Thomas     7.0     8.0     7.0         0.0
497  SMIT/DSAI/498           Jacob Simon     9.0     1.0    10.0        10.0
498  SMIT/DSAI/499        Kimberly Ayers     9.0     7.0     1.0         3.0
499  SMIT/DSAI/500           Alvin Brown     9.0     7.0     8.0         0.0

[500 rows x 6 columns]

In [106]:
student_data.isna().sum()

roll_no       0
name          0
quiz_1        0
quiz_2        0
quiz_3        0
final_exam    0
dtype: int64

In [107]:
student_data.max(numeric_only=True)

quiz_1        10.0
quiz_2        10.0
quiz_3        10.0
final_exam    40.0
dtype: float64

In [108]:
student_data.min(numeric_only=True)

quiz_1         0.0
quiz_2        -2.0
quiz_3        -1.0
final_exam   -34.0
dtype: float64

In [109]:
student_data.replace(-1,0).min()

roll_no       SMIT/DSAI/001
name             Aaron Rowe
quiz_1                  0.0
quiz_2                 -2.0
quiz_3                  0.0
final_exam            -34.0
dtype: object

In [110]:
nn = student_data[student_data.iloc[:, 2:] >= 0]

In [111]:
student_data.iloc[:,2:] = nn.iloc[:,2:].fillna(0)

In [112]:
student_data.min(numeric_only=True)

quiz_1        0.0
quiz_2        0.0
quiz_3        0.0
final_exam    0.0
dtype: float64

In [113]:
student_data.describe()

           quiz_1      quiz_2      quiz_3  final_exam
count  500.000000  500.000000  500.000000  500.000000
mean     4.328000    4.410000    4.450000   17.832000
std      3.328449    3.318422    3.358282   12.782745
min      0.000000    0.000000    0.000000    0.000000
25%      1.000000    1.000000    1.000000    6.750000
50%      4.000000    4.000000    4.000000   17.000000
75%      7.000000    7.000000    7.000000   29.000000
max     10.000000   10.000000   10.000000   40.000000

In [114]:
student_data.head()

         roll_no                  name  quiz_1  quiz_2  quiz_3  final_exam
0  SMIT/DSAI/001         Thomas Mcneil     6.0     1.0     6.0         6.0
1  SMIT/DSAI/002       Brian Davis Jr.     3.0     2.0     7.0         3.0
2  SMIT/DSAI/003  Christopher Thompson    10.0     8.0     2.0         7.0
3  SMIT/DSAI/004          Thomas Ortiz     7.0     0.0     5.0        19.0
4  SMIT/DSAI/005      Benjamin Aguirre     4.0     3.0     0.0        28.0

In [115]:
student_data["obtain"] = student_data.iloc[:,2:].sum(axis=1)

In [116]:
student_data.head()

,roll_no,name,quiz_1,quiz_2,quiz_3,final_exam,obtain
0,SMIT/DSAI/001,Thomas Mcneil,6.0,1.0,6.0,6.0,19.0
1,SMIT/DSAI/002,Brian Davis Jr.,3.0,2.0,7.0,3.0,15.0
2,SMIT/DSAI/003,Christopher Thompson,10.0,8.0,2.0,7.0,27.0
3,SMIT/DSAI/004,Thomas Ortiz,7.0,0.0,5.0,19.0,31.0
4,SMIT/DSAI/005,Benjamin Aguirre,4.0,3.0,0.0,28.0,35.0

In [117]:
student_data["total"] = 70

In [118]:
student_data["per"] = (student_data.obtain / student_data.total) * 100

In [119]:
student_data.head(10)

,roll_no,name,quiz_1,quiz_2,quiz_3,final_exam,obtain,total,per
0,SMIT/DSAI/001,Thomas Mcneil,6.0,1.0,6.0,6.0,19.0,70,27.142857
1,SMIT/DSAI/002,Brian Davis Jr.,3.0,2.0,7.0,3.0,15.0,70,21.428571
2,SMIT/DSAI/003,Christopher Thompson,10.0,8.0,2.0,7.0,27.0,70,38.571429
3,SMIT/DSAI/004,Thomas Ortiz,7.0,0.0,5.0,19.0,31.0,70,44.285714
4,SMIT/DSAI/005,Benjamin Aguirre,4.0,3.0,0.0,28.0,35.0,70,50.000000
5,SMIT/DSAI/006,Amanda Walls,6.0,9.0,6.0,9.0,30.0,70,42.857143
6,SMIT/DSAI/007,Karen Harrison,9.0,4.0,0.0,33.0,46.0,70,65.714286
7,SMIT/DSAI/008,Steven Allen,0.0,1.0,8.0,25.0,34.0,70,48.571429
8,SMIT/DSAI/009,Michael Copeland,6.0,10.0,0.0,40.0,56.0,70,80.000000
9,SMIT/DSAI/010,Jennifer Schneider,10.0,7.0,0.0,2.0,19.0,70,27.142857

In [120]:
def grade(marks):
    if marks>80:
        return 'A'
    elif marks>70:
        return 'B'
    elif marks>50:
        return 'C'
    else:
        return 'F'

In [121]:
student_data["Grade"] = student_data.per.apply(grade)

In [122]:
student_data.Grade.value_counts()

Grade
F    304
C    138
B     42
A     16
Name: count, dtype: int64

In [123]:
student_df = pd.read_csv("students_five_classes.csv")
student_df

           roll_no           name  exam1  exam2  final_exam
0    SMIT/DSAI/001    David Iqbal     20     16          35
1    SMIT/DSAI/002    Ahmed Ahmed     13      7          40
2    SMIT/DSAI/003     John Zahid     13     24          47
3    SMIT/DSAI/004    David Brown      0     15          24
4    SMIT/DSAI/005    Fatima Khan     20      8           6
..             ...            ...    ...    ...         ...
495   SMIT/MAW/096     Sara Zahid      8     10          45
496   SMIT/MAW/097     Ayesha Ali     14      3          31
497   SMIT/MAW/098  Michael Brown      2     20          50
498   SMIT/MAW/099     Sara Malik     24      6          16
499   SMIT/MAW/100       Noor Ali      9     11          44

[500 rows x 5 columns]

In [128]:
student_df["class"] = student_df.roll_no.str.split('/').str[1]

In [131]:
student_df['class'].unique()

array(['DSAI', 'DM', 'UIUX', 'GD', 'MAW'], dtype=object)

In [124]:
def return_class(x):
    return x.split('/')[1]
student_df.roll_no.apply(return_class)

0      DSAI
1      DSAI
2      DSAI
3      DSAI
4      DSAI
       ...
495     MAW
496     MAW
497     MAW
498     MAW
499     MAW
Name: roll_no, Length: 500, dtype: str

In [127]:
student_df.roll_no.str.split('/').str[1]

0      DSAI
1      DSAI
2      DSAI
3      DSAI
4      DSAI
       ...
495     MAW
496     MAW
497     MAW
498     MAW
499     MAW
Name: roll_no, Length: 500, dtype: object