In [1]:
import pandas as pd

In [2]:
calories = pd.read_csv("calories.csv")

In [3]:
calories

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [13]:
data = [["Yasir","Nawaz",50,60,80,50,90],
        ["Yasir1","Nawaz",89,90,40,70,60],
        ["Yasir1","Nawaz",89,90,40,70,60],
        ["Yasir1","Nawaz",89,90,40,70,60],
        ["Yasir1","Nawaz",89,90,40,70,60],
        ["Yasir2","Nawaz",90,50,60,80,70]]

In [15]:
df = pd.DataFrame(data,columns=["Name","FName","S1","S2","S3","S4","S5"],index=[f"std{x}" for x in range(len(data))])

In [16]:
df

        Name  FName  S1  S2  S3  S4  S5
std0   Yasir  Nawaz  50  60  80  50  90
std1  Yasir1  Nawaz  89  90  40  70  60
std2  Yasir1  Nawaz  89  90  40  70  60
std3  Yasir1  Nawaz  89  90  40  70  60
std4  Yasir1  Nawaz  89  90  40  70  60
std5  Yasir2  Nawaz  90  50  60  80  70

In [21]:
se = pd.Series([1,2,3])

In [22]:
se

0    1
1    2
2    3
dtype: int64

In [27]:
data = [{"Name":"Yasir","FName":"Nawaz","S1":50,"S2":60,"S3":80,"S4":50,"S5":90},
       {"Name":"Yasir","FName":"Nawaz","S1":50,"S2":60,"S3":80,"S4":50,"S5":90},
       {"Name":"Yasir","FName":"Nawaz","S1":50,"S2":60,"S3":80,"S4":50,"S5":90},
       {"Name":"Yasir","FName":"Nawaz","S1":50,"S2":60,"S3":80,"S4":50,"S5":90}]

In [28]:
df1 = pd.DataFrame(data)

In [29]:
df1

    Name  FName  S1  S2  S3  S4  S5
0  Yasir  Nawaz  50  60  80  50  90
1  Yasir  Nawaz  50  60  80  50  90
2  Yasir  Nawaz  50  60  80  50  90
3  Yasir  Nawaz  50  60  80  50  90